### ISSUE TITLE
'SBDObject' object has no attribute 'timestamp'

### ISSUE THREAD

**Issue by alphafox02** [muccc/iridium-toolkit#54]
I pulled down last night's version of gr-iridium (3.8 branch) and iridium toolkit. I'm working on updating DragonOS Focal  (20.04 based w/ python 3.8.10) and learning about the new acars feature. When I run the iridium extractor with this line,

iridium-extractor -D 4 --multi-frame /usr/src/gr-iridium/examples/rtl-sdr-soapy.conf | python3 -u /usr/src/iridium-toolkit/iridium-parser.py -o zmq

And the toolkit in a second terminal like this,

python3 -u /usr/src/iridium-toolkit/reassembler.py -m acars zmq:

The second terminal eventually ends up like this,

Traceback (most recent call last):
  File "/usr/src/iridium-toolkit/reassembler.py", line 1856, in <module>
    zx.run(iter(socket.recv_string,""))
  File "/usr/src/iridium-toolkit/reassembler.py", line 205, in run
    self.consume(mo)
  File "/usr/src/iridium-toolkit/reassembler.py", line 1104, in consume
    self.consume_l2(zz)
  File "/usr/src/iridium-toolkit/reassembler.py", line 1366, in consume_l2
    out += q.timestamp + " "
AttributeError: 'SBDObject' object has no attribute 'timestamp'

I've not seen any acars messages and sometimes the timestamp traceback happens shortly after l launch and other times it'll run for awhile before having the issue.

**Comment by alphafox02** [comment]
Perfect. 
![0DC52CAC-2A66-4CB3-B1B6-B3916823C846](https://user-images.githubusercontent.com/44436101/156885950-6d8761b5-b178-4f25-b0a0-ab1c10493642.jpeg)

**Comment by alphafox02** [comment]
I didn't know if I should open another ticket, but ended up getting this after letting it run for some time.

Traceback (most recent call last):
  File "/usr/src/iridium-toolkit/reassembler.py", line 1862, in <module>
    zx.run(iter(socket.recv_string,""))
  File "/usr/src/iridium-toolkit/reassembler.py", line 205, in run
    self.consume(mo)
  File "/usr/src/iridium-toolkit/reassembler.py", line 1104, in consume
    self.consume_l2(zz)
  File "/usr/src/iridium-toolkit/reassembler.py", line 1415, in consume_l2
    out+="SEQ: %s, FNO: %s"%(ascii(elf.seqn, escape=True), ascii(q.f_no, escape=True))
NameError: name 'elf' is not defined
